[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(nav, esc)
esc = grave

[nav]
w = up
a = left
s = down
d = right

[alt]
# WASD to Arrows
# w = up
# a = left
# s = down
# d = right
# vim to arrows too
# k = up
# h = left
# j = down
# l = right

# 1234 to Multimedia Keys
1 = playpause
2 = previoussong
3 = nextsong
4 = mute
